using System;

namespace Wander.NeST
{
  /// A deserialization helper that given a byte array allows you to deserialize
  /// objects from it until the end of the array.
  public class Deserializer
  {
    public bool HasData { get { return array.HasNext(); } }

    ByteArray array;

    public Deserializer(ByteArray array)
    {
      if (array == null) 
        throw new ArgumentNullException("array");

      this.array = array;      
    }

    /// Deserialize an ISerializable from this object's internal byte array.
    public T Deserialize<T>() where T : ISerializable, new()
    {
      T t = new T();
      t.DeserializeFrom(this);
      return t;
    }

    /// Deserialize an object using a reader function that implements how the
    /// object should be serialized.
    public T DeserializeUsing<T>(Readers.Reader<T> reader)
    {
      T value;
      array.Increment(reader(out value, array.Array, array.Position));
      return value;
    }

    #region autogenerated-deserializing-methods
    /* ***AUTO-GENERATED*** 
     * Given readers, these methods return a structure of variables of the types
     * defined in the parameters. */
    public
    Deserialized<A, B>
    DeserializeUsing<A, B>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB
    )
    {
      var v =
        new Deserialized<A, B>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C>
    DeserializeUsing<A, B, C>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC
    )
    {
      var v =
        new Deserialized<A, B, C>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D>
    DeserializeUsing<A, B, C, D>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD
    )
    {
      var v =
        new Deserialized<A, B, C, D>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E>
    DeserializeUsing<A, B, C, D, E>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE
    )
    {
      var v =
        new Deserialized<A, B, C, D, E>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F>
    DeserializeUsing<A, B, C, D, E, F>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G>
    DeserializeUsing<A, B, C, D, E, F, G>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H>
    DeserializeUsing<A, B, C, D, E, F, G, H>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I>
    DeserializeUsing<A, B, C, D, E, F, G, H, I>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J, K>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J, K>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ, 
      Readers.Reader<K> readerK
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J, K>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      array.Increment(readerK(out v.k, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J, K, L>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J, K, L>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ, 
      Readers.Reader<K> readerK, Readers.Reader<L> readerL
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J, K, L>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      array.Increment(readerK(out v.k, array.Array, array.Position));
      array.Increment(readerL(out v.l, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J, K, L, M>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ, 
      Readers.Reader<K> readerK, Readers.Reader<L> readerL, 
      Readers.Reader<M> readerM
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      array.Increment(readerK(out v.k, array.Array, array.Position));
      array.Increment(readerL(out v.l, array.Array, array.Position));
      array.Increment(readerM(out v.m, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M, N>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ, 
      Readers.Reader<K> readerK, Readers.Reader<L> readerL, 
      Readers.Reader<M> readerM, Readers.Reader<N> readerN
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M, N>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      array.Increment(readerK(out v.k, array.Array, array.Position));
      array.Increment(readerL(out v.l, array.Array, array.Position));
      array.Increment(readerM(out v.m, array.Array, array.Position));
      array.Increment(readerN(out v.n, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ, 
      Readers.Reader<K> readerK, Readers.Reader<L> readerL, 
      Readers.Reader<M> readerM, Readers.Reader<N> readerN, 
      Readers.Reader<O> readerO
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      array.Increment(readerK(out v.k, array.Array, array.Position));
      array.Increment(readerL(out v.l, array.Array, array.Position));
      array.Increment(readerM(out v.m, array.Array, array.Position));
      array.Increment(readerN(out v.n, array.Array, array.Position));
      array.Increment(readerO(out v.o, array.Array, array.Position));
      return v;
    }

    public
    Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>
    DeserializeUsing<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
      Readers.Reader<A> readerA, Readers.Reader<B> readerB, 
      Readers.Reader<C> readerC, Readers.Reader<D> readerD, 
      Readers.Reader<E> readerE, Readers.Reader<F> readerF, 
      Readers.Reader<G> readerG, Readers.Reader<H> readerH, 
      Readers.Reader<I> readerI, Readers.Reader<J> readerJ, 
      Readers.Reader<K> readerK, Readers.Reader<L> readerL, 
      Readers.Reader<M> readerM, Readers.Reader<N> readerN, 
      Readers.Reader<O> readerO, Readers.Reader<P> readerP
    )
    {
      var v =
        new Deserialized<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>();
      array.Increment(readerA(out v.a, array.Array, array.Position));
      array.Increment(readerB(out v.b, array.Array, array.Position));
      array.Increment(readerC(out v.c, array.Array, array.Position));
      array.Increment(readerD(out v.d, array.Array, array.Position));
      array.Increment(readerE(out v.e, array.Array, array.Position));
      array.Increment(readerF(out v.f, array.Array, array.Position));
      array.Increment(readerG(out v.g, array.Array, array.Position));
      array.Increment(readerH(out v.h, array.Array, array.Position));
      array.Increment(readerI(out v.i, array.Array, array.Position));
      array.Increment(readerJ(out v.j, array.Array, array.Position));
      array.Increment(readerK(out v.k, array.Array, array.Position));
      array.Increment(readerL(out v.l, array.Array, array.Position));
      array.Increment(readerM(out v.m, array.Array, array.Position));
      array.Increment(readerN(out v.n, array.Array, array.Position));
      array.Increment(readerO(out v.o, array.Array, array.Position));
      array.Increment(readerP(out v.p, array.Array, array.Position));
      return v;
    }
    #endregion
  }
}